### ISSUE TITLE
Set voicetrack group - v4.0.0beta1 Ubuntu Studio

### ISSUE THREAD

**Issue by RudiOnTheAir** [ElvishArtisan/rivendell#684] opened 2021-07-07 17:14 UTC
Hi
I'm testings v4.0.0beta1 on Ubuntu Studio. Have imported my v3.6 database and wonder that i can't set the voicetrack group in rdadmin/edit-service.
Can't change from [none] to my existing group.

**Comment by ElvishArtisan** [comment] 2021-07-08 16:19
Unable to reproduce this problem here. Question: are there any groups listed in the 'Voicetrack Group' drop-down besides '[none]'? If there are, are all of the existing groups visible, or only some?

**Comment by RudiOnTheAir** [comment] 2021-07-09 11:52
No, there is no group listed. On klick i can see the [none] two times...But no other.

**Comment by RudiOnTheAir** [comment] 2021-07-23 14:59
I've openen rdadmin in terminal and after that "manage service" > "Production". Could that be the reason for the empty group pulldowns..?
Btw, the QT5 branch has not the error with a new fresh database. The via script installed master branch has an imported database from my production system (latest 3.x) 

DB connection re-established
invalid SQL or failed DB connection[You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'GROUPS order by NAME' at line 1 QMYSQL: Unable to execute query]: select NAME from GROUPS order by NAME

**Comment by ElvishArtisan** [comment] 2021-07-27 17:34
Fixed in ede949fa1.

**Closed by ElvishArtisan** 2021-07-27 17:34 UTC
Labels: question
