### ISSUE TITLE
Another Crash in rdlogmanager 4.0.0beta3 While Generating Report

### ISSUE THREAD

**Issue by dklann** [ElvishArtisan/rivendell#794] opened 2022-03-31 16:02 UTC
After testing the fix for #792 I encountered a crash while generating a report. Seems to be a different issue.
Invoking with `rdlogmanager -r SX -s Production` I get the error:
_QWidget: Cannot create a QWidget without QApplication_

Here is the stack trace:
```                Stack trace of thread 4955:
                #0  0x00007f8cd813903b __GI_raise (libc.so.6 + 0x4303b)
                #1  0x00007f8cd8118859 __GI_abort (libc.so.6 + 0x22859)
                #2  0x00007f8cd87fbaad _ZNK14QMessageLogger5fatalEPKcz (libQt5Core.so.5 + 0x85aad)
                #3  0x00007f8cd961a642 n/a (libQt5Widgets.so.5 + 0x15f642)
                #4  0x00007f8cd9828e43 _ZN7QDialogC1EP7QWidget6QFlagsIN2Qt10WindowTypeEE (libQt5Widgets.so.5 + 0x36de43)
                #5  0x00007f8cda98d2ba _ZN8RDDialogC2EP7QWidget6QFlagsIN2Qt10WindowTypeEE (librd-4.0.0beta3.so + 0x3182ba)
                #6  0x00007f8cda9ec126 _ZN8RDGetAthC2EPdP7QWidget (librd-4.0.0beta3.so + 0x377126)
                #7  0x00007f8cda8aa1c4 _ZN8RDReport13ExportSoundExERK7QStringRK5QDateS5_S2_ (librd-4.0.0beta3.so + 0x2351c4)
                #8  0x00007f8cdaafe028 _ZN8RDReport14generateReportERK5QDateS2_P9RDStationP7QString (librd-4.0.0beta3.so + 0x489028)
                #9  0x000055f9a21864b2 _Z18RunReportOperationiPPcRK7QStringbii (rdlogmanager + 0x304b2)
                #10 0x000055f9a217fbdf main (rdlogmanager + 0x29bdf)
                #11 0x00007f8cd811a0b3 __libc_start_main (libc.so.6 + 0x240b3)
                #12 0x000055f9a217ff7e _start (rdlogmanager + 0x29f7e)
```

**Comment by ElvishArtisan** [comment] 2022-04-01 17:13
Confirmed here.

**Comment by ElvishArtisan** [comment] 2022-04-02 00:57
'Kay, turns out that your test had the misfortune to use the one report type that requires the user to supply an additional parameter during report generation (the _aggregate tuning hours_ parameter, for the __SoundExchange Statutory License__ report type). The default generator puts up a dialog to prompt the user for the value, but with no X11 context it fails and generates the above ugly error.

Fixed in 3cc7806. You now need to supply an '-h <hours>' option when running this report from the command line, or you will get a (hopefully much less obnoxious) '-h option required' error. The GUI version works as before.

Please test!

**Comment by dklann** [comment] 2022-04-02 15:42
Confirming commit 3cc7806 fixes this issue for me.

**Comment by ElvishArtisan** [comment] 2022-04-18 18:28
Thank you!

**Closed by ElvishArtisan** 2022-04-18 18:28 UTC
Labels: bug, question
