### ISSUE TITLE
RDLibrary can't enter a blank cart year

### ISSUE THREAD

**Issue by wilson500** [ElvishArtisan/rivendell#491] opened 2019-09-03 15:56 UTC
Rivendell 3.03 - Ubuntu 18.04

You can't remove a year from a cart.
Emptying the field in RDLibrary and pressing OK gives this error:

`invalid SQL or failed DB connection[Incorrect date value: '-001-01-01' for column 'YEAR' at row 1 QMYSQL: Unable to execute query]: update CART set YEAR="-001-01-01" where NUMBER=10005`

**Comment by deltecent** [comment] 2019-09-03 16:59
Cannot reproduce on CentOS 7. It's becoming clear that we need to consider an official Debian development track and release.

**Comment by ElvishArtisan** [comment] 2019-09-03 17:06
Confirmed here. This doesn't manifest on CentOS because MariaDB is configured there to be more tolerant of ill-formed SQL.

**Comment by ElvishArtisan** [comment] 2019-09-03 17:18
Fixed in c31c267.

**Closed by ElvishArtisan** 2019-09-03 17:18 UTC
Labels: bug
