### ISSUE TITLE
Logitek vGuest Inoperable v4.0.0beta3 (2458206)

### ISSUE THREAD

**Issue by aspinwalld** [ElvishArtisan/rivendell#758] opened 2021-11-21 01:17 UTC
There look to be a few issues with Logitek vGuest Switcher/GPIO in v4.0.0beta3 (running on CentOS7).

When creating a new Switcher/GPIO device of the type Logitek vGuest, the `IP Address` and `IP Port` fields seem to be reset null when OK is clicked. If the Primary Connection type is set to None instead of TCP/IP, the fields now remain, but a quick PCAP shows no vGuest traffic (as expected).

Also, when editing vGuest Switches, field mapping looks incorrect. Let's say I map the following values in vGuest Switch editor:

- Engine = 0001
- Device (Hex) = 0002
- Surface = 0003
- Bus/Relay = 0004

They will show as follows in the vGuest Switch list:
- Engine = 0001
- Device (Hex) = 0002
- Surface = 0002
- Bus/Relay = 0003

Also, what is the reason behind changing the type/validation from Hex (as in v3.6.2) to Decimal? Do new versions of Logitek software display data in decimal? I'm on a circa 2000 AE32 v2 audio engine using Logitek Supervisor v3.6 which displays all information in hex, so having to do the conversions from hex to decimal and back again to map switches seems unnecessary.

I can provide more data if needed, and this *should* be easy to reproduce.

**Comment by ElvishArtisan** [comment] 2021-12-02 22:26
> Also, what is the reason behind changing the type/validation from Hex (as in v3.6.2) to Decimal? Do new versions of Logitek software display data in decimal? I'm on a circa 2000 AE32 v2 audio engine using Logitek Supervisor v3.6 which displays all information in hex, so having to do the conversions from hex to decimal and back again to map switches seems unnecessary.

The reason was a comment from one of Logitek's support people that _only_ the device numbers should be hexidecimal; with all others (engines, busses, etc) being rendered in decimal.

**Comment by ElvishArtisan** [comment] 2021-12-02 22:52
Confirmed here.

**Comment by ElvishArtisan** [comment] 2021-12-02 22:59
Fixed in 65fed04. Please test!

**Closed** 2022-01-10 17:00 UTC
Labels: bug, question
