### ISSUE TITLE
Dropbox - Segue Marker Value -1200 insted of -12 (Rivendell v4 rc1)

### ISSUE THREAD

**Issue by radiocafero** [ElvishArtisan/rivendell#862] opened 2023-01-12 12:37 UTC
Something is wrong in dropbox line deployment.
When you put Segue Level @ -12db, in task process it is something else and it show -1200.
Of course no segue marker will be match in dropbox task.

**Comment by RudiOnTheAir** [comment] 2023-01-12 12:51
Known problem in older v3. Not yet tested on v4... Thats why i use only shellscripts to import direct via rdimport. But it would be nice to create dropboxes via GUI...:)

**Comment by radiocafero** [comment] 2023-01-12 13:58
Not a problem with rdimport. I just want to help to bug tracking.

**Comment by ElvishArtisan** [comment] 2023-01-18 14:45
Confirmed here.

**Comment by RudiOnTheAir** [comment] 2023-01-20 10:15
HiI recompiled and tested.
Now the values ​​are correctly passed to the rdimport process.

Thanks for the fix

Am Mittwoch, Januar 18, 2023 15:54 CET, schrieb Fred Gleason ***@***.***>:
 
 
Fixed in 567fe75. Please test!
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***>[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/ElvishArtisan/rivendell/issues/862#issuecomment-1387202506", "url": "https://github.com/ElvishArtisan/rivendell/issues/862#issuecomment-1387202506", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]***>
-- 
MfG
Wolf-Rüdiger Schwoon
https://radio-phonhaus.de
https://mastodon.nordsee.social/

**Closed** 2023-01-23 15:08 UTC
Labels: bug, question
