### ISSUE TITLE
Single Quotes Disallowed In Macro Carts

### ISSUE THREAD

**Issue by RichStivers** [ElvishArtisan/rivendell#370] opened 2019-02-03 10:03 UTC
Starting with v2.19.3, single quotes are disallowed in Macro Carts while adding/editing lines in RDLibrary.
Before v2.19.3, single quotes were allowed.

**Comment by deltecent** [comment] 2019-02-03 18:56
Would you provide an example of the line(s) you are trying to add/edit?

**Comment by RichStivers** [comment] 2019-02-03 21:37
RN /usr/local/bin/load-cart.sh 2201 'Blues Marathon Promo 1'!

**Comment by ElvishArtisan** [comment] 2019-02-04 13:08
Confirmed present in v3.0.0beta00 as well.

I would say that this definitely touches an under-specified facet of RML, namely: what are the quoting and escaping rules? How, for example, should one include a '!' in a string literal argument to something like ['LB']?

**Comment by RichStivers** [comment] 2019-02-05 21:47
What if RML allowed a hex expression for literal ascii characters such as 0x21 for a literal '!'  ?

**Comment by deltecent** [comment] 2019-02-07 16:22
The first issue is probably a regression. The edit macro line simply doesn't accept a ```'``` character from the keyboard. I was trying to enter ```LB Spring Creek's Positive Mix!``` and the text box will only allow ```Spring Creeks Positive Mix```. I recall fixing this somewhere else and will push a PR.

**Comment by deltecent** [comment] 2019-02-07 16:29
Fred will have to weight in on this one. I see no reason why the macro has to run through ```RDTextValidator``` and "validate a string as being valid for a SQL text datatype".

**Comment by ElvishArtisan** [comment] 2019-02-07 19:11
Looks like it was a change in the underlying ```RDTextValidator``` class that had an unintentional ripple effect. I see no real reason to have character restrictions on RMLs, so I've gone ahead and removed it from the dialog.

Fixed in [master e6fb2db].

**Closed by ElvishArtisan** 2019-02-07 19:11 UTC
