### ISSUE TITLE
Rdairplay log edits

### ISSUE THREAD

**Issue by ctecamp** [ElvishArtisan/rivendell#434] opened 2019-05-26 13:52 UTC
Moving a cart in the cart stack is not reflected in the right log panel.
When adding a cart to right log panel it doesn't show, however does show in the cart stack. Basically any changes to the log are not reflected in the right log panel.
Rivendell-3.0rc02.0 running on Debian 9.

**Comment by deltecent** [comment] 2019-05-27 19:26
In 3.0.0rc02 I am not seeing any problems with adding/deleting carts to either the left or right log widgets, but I am seeing a problem with moving carts. This seems to happen when selecting the cart to "move" using the right log and the "to" location using the left buttons.  The cart is removed from the right log but not placed in its new location. Generating another change updates/fixes the right log.
Rivendell-3.0rc02.0 running on CentOS 7.

**Comment by ctecamp** [comment] 2019-05-27 23:21
Agreed however copying also produces some unexpected results. Like placing
copied item at the top of the right widget instead of where it was placed.
In my testing here all these problems seem to be with right widget on the
left widget things go to the correct place.

Anyway pretty confusing to a operator trying to run a show.

Tim Camp
WZEW-FM

**Comment by ctecamp** [comment] 2019-05-28 00:03
I don't remember ever seeing this behavior on rc01 or 00.
Think I'm going to roll back and see.

Tim Camp
WZEW FM

**Comment by deltecent** [comment] 2019-05-28 00:14
I've been trying for about an hour to get it to fail using only the right widget. I cannot make it fail. Would you be able to provide the exact steps you're doing?

**Comment by ctecamp** [comment] 2019-05-28 00:56
On the right widget if I select an item near the bottom of the widget and
move it to any other position it shows up in the right widget at the very
top of the log.
On the left widget it shows up in the correct place. If I move or copy
another item in the right widget it goes to the top of the log but the
first item I moved then drops into the correct location.
So the overall behavior is that whatever I move or copy it goes to the top
of the log then corrects itself on the next move or change.
I have the exact same experience on two different installs, one on Debian 9
the other on Ubuntu 18.04.

Moved or copied items always show in the correct position on the left
widget.

Tim Camp
WZEW-FM

**Comment by ctecamp** [comment] 2019-05-28 01:00
I forgot to mention the other peculiar thing, the moved or copied item
changes in its new position from Seque to Play.

Default setting for rdairplay is Seque.

Tim Camp
WZEW-FM

**Comment by ctecamp** [comment] 2019-05-28 01:03
Greetings again,
I thought I should mention this is happening with the log that was manually
created.

**Comment by ctecamp** [comment] 2019-05-28 20:33
Greetings,

This behavior is on rc02....
Rivendell 3.0 beta and 01 do not exhibit this.

Cheers

Tim Camp
WZEW-FM

**Comment by ElvishArtisan** [comment] 2019-06-04 22:34
AFAICT, we have had 'squirrelly' behavior in this area since the Qt4 port. One test that seems consistently repeatable:

1) Start rdairplay(1)
2) Load a log into the Main Log machine
3) Click the 'Move` button at the bottom left-hand side.
4) Click the first line in the right-hand log, then the 'MOVE' button in the right-hand section.
5) Click the bottom-most 'To?' button on the left-hand side.

The item selected from the right-hand side appears on the left, but is not removed from the right-hand side.

I've confirmed that this exists at least as far back as v3.0.0beta00. It is *not* present in v2.19.3, therefore I'm concluding that its a regression that likely occurred during the Qt3=>Qt4 port. I suspect that the other weirdnesses reported here are related.

**Comment by ElvishArtisan** [comment] 2019-06-07 21:49
Fixed in [master cb74a4b].

**Closed by ElvishArtisan** 2019-06-07 21:49 UTC
Labels: bug
