### ISSUE TITLE
4.2.2 Bug? Timed carts do not show as blue in cart list

### ISSUE THREAD

**Issue by vizubeat** [ElvishArtisan/rivendell#957] opened 2024-05-04 21:49 UTC
I'm pretty sure that previous versions showed timed events in blue to more easily distinguish them in the cart list. They are still blue in the log view, but it would be super handy if the times of S and H timed events showed as blue/bold in the list of loaded carts - see 
![this](https://github.com/ElvishArtisan/rivendell/assets/93675293/751832a0-69e9-4e08-9759-cf78fecb52d0)

**Comment by ElvishArtisan** [comment] 2024-05-08 19:26
Confirmed here.

**Comment by ElvishArtisan** [comment] 2024-05-08 19:27
Fixed in 09823c5. Please test!

**Comment by vizubeat** [comment] 2024-05-12 17:32
I cannot compile from source. Just know that I'm trying to help in testing :-) 

<img width="649" alt="Screenshot 2024-05-12 at 18 25 33" src="https://github.com/ElvishArtisan/rivendell/assets/93675293/cf0a72ae-3ac4-4eb6-aa2d-714938a0c257">

...that must be a me thing, but I've read and understand the changes in 09823c5 and it looks great - thank you!

**Comment by dklann** [comment] 2024-05-14 16:59
Confirmed blue text in the left-hand panel, in commit 8b0dbf57 here.

**Comment by ElvishArtisan** [comment] 2024-05-14 18:54
@vizubeat: looks like you're missing the DocBook5 stylesheets. See https://wiki.rivendellaudio.org/index.php/Building_Rivendell_from_source and do a search for the phrase 'DOCBOOK_STYLESHEETS'.

**Closed as completed** 2024-05-14 18:55 UTC
Labels: bug, question
