### ISSUE TITLE
RDLibrary Bug

### ISSUE THREAD

**Issue by Chester-Graham** [ElvishArtisan/rivendell#589] opened 2020-05-30 01:45 UTC
If you have multiple cuts in a cart and choose to mass delete them, 
1 - Select Order by Number (not sure if this makes any difference)
2 - Select the first cut to delete
3 - Shift select the last cut of the range to delete BELOW the first cut (top down selection process)
---- This works properly---
2 - Select the first cut to delete at the bottom of the desired list
3 - Shift select the last cut of the range to delete at the TOP of the desired list (reversed selection process)
RDLibrary hard crashes!

**Comment by Chester-Graham** [comment] 2020-05-30 01:50
Also will crash if I select 12 cuts from top to bottom.

**Comment by ElvishArtisan** [comment] 2020-06-07 16:19
After several dozen tests, I have not been able to reproduce this here as yet.

**Comment by Chester-Graham** [comment] 2020-06-07 21:35
Thanks, I'll keep watching for it. I have had it happen 3 or 4 times, usually after an extended dropbox import of multiple files into the same cart that are up to an hour long. Occasionally I forget to change the cart that the dropbox is configured for and end up importing an string of files into the wrong cart. I copied and moved them one at a time from that cart to the new correct cart, and then attempted to bulk delete them. That was when I would experience the crashes. Thought I had a reproducible pattern, but now, just putting a bunch in and deleting them doesn't seem to crash. This has been in 3.3.0, and the last series of crashes I had in 3.4.0. When I reported I had reproduced the crash about 3 times in a row, but then it stopped being reproduced.

**Comment by ElvishArtisan** [comment] 2020-06-09 13:28
Got it!
Your extra info was very helpful! Turns out that all you need to do to reliably goose this is hit the __Copy__ button on a cut, then select a range of cuts and try to delete them.

**Comment by ElvishArtisan** [comment] 2020-06-09 13:56
Fixed in f2ed0c1. Please test!

**Comment by Chester-Graham** [comment] 2020-06-11 00:15
I am thankful that you were able to reproduce a crash. I don't have the ability to test until it is rolled out in a release. Thanks.

**Comment by ElvishArtisan** [comment] 2020-06-11 12:37
'Kay. I'm closing this for the time being then.

**Closed by ElvishArtisan** 2020-06-11 12:37 UTC
Labels: bug, question
