### ISSUE TITLE
RD400b3 possible rdairplay missing carts from another group bug

### ISSUE THREAD

**Issue by zotz** [ElvishArtisan/rivendell#829] opened 2022-09-29 11:33 UTC
The problem was brought to my attention on the FB group. I was able to duplicate but have not fully explored.

If I go to add a cart, carts from a group  that was added (in this case Alab) do not show when All groups are requested yet when the single group is requested, the cart(s) in t hat group do show.

I am attaching screenshots to illustrate.

drew

![rd40b3airplaymissingcarts01](https://user-images.githubusercontent.com/614926/193020739-3a9a9d2c-3f97-4738-bfec-befb315abb35.png)

![rd40b3airplaymissingcarts02](https://user-images.githubusercontent.com/614926/193020757-8a5bdae5-f1a1-4710-8b38-303aef200118.png)

**Comment by ElvishArtisan** [comment] 2022-09-29 18:14
Unable to reproduce here. Could you post a step-by-step procedure that gooses it?

**Comment by ElvishArtisan** [comment] 2022-09-29 18:19
> The problem was brought to my attention on the FB group. 

Speaking of the FB group -- how might one go about getting access to that? (Seeing as Google has made it effectively impossible to maintain private listservs with any kind of decent reliability, I should probably start hanging out there).

**Comment by zotz** [comment] 2022-09-29 20:48
I sent you a message on FB with a link that I hope gets you there. If not, let me know and we can try something else.

**Comment by zotz** [comment] 2022-09-29 20:57
Basic step by step.

1. Closed rdairplay.
2. Added new group Alab with a description of Alab desc
3. Started rdairplay.
4. clicked on Add button.
5. problem showed up.

Note, I had a report and just at least partially confirmed. This issue is not confined to rdairplay. I just saw the same issue in rdlibrary.

**Comment by ElvishArtisan** [comment] 2022-09-30 19:33
Still unable to reproduce. Using CentOS 7. Here's the detailed blow-by-blow procedure followed:

1. Restart the rivendell service ('systemctl restart rivendell', as root)
2. Start and log into rdadmin(1)
3. Click 'Manage Groups', followed by  'Add' buttons
4. Enter 'Alab' in the 'New Group Name' field, then click 'OK'.
5. Enter 'Alab desc' in the 'Group Description' field, then click 'OK'.
6. Click 'Close' on the 'Rivendell Group List' dialog, followed by 'Quit' on the main rdadmin(1) window. rdadmin(1) exists.
7. Start rdairplay(1) and click 'Add'. The 'Select Cart' dialog opens.
8. Click the 'Group' dropdown. 'Alab' appears as the first entry on the list.

At what point do things diverge from the above for you?

**Comment by zotz** [comment] 2022-10-01 13:55
Trying to attach a screen grab video that might explain  things better.
[rivbug829_01.webm](https://user-images.githubusercontent.com/614926/193412930-bb0554ec-9426-4fa7-96c3-0e110d2db778.webm)

**Comment by dklann** [comment] 2022-10-04 16:32
I am also unable to reproduce this with Rivendell 4.0.0rc1 on Linux Mint 21, Xfce (based on Ubuntu 22.04). I followed the steps listed by @ElvishArtisan [above](https://github.com/ElvishArtisan/rivendell/issues/829#issuecomment-1263942953) and the sole Cart in the "new" Group appeared in the Cart list.

Could this be a "Rivendell user" issue with the installation?

**Comment by zotz** [comment] 2022-10-04 19:27
First, I just duplicated the setup and a fresh 3.x installed in a VM today. I do not see the issue there.

Second, I just replaced all the cuts in my 4.x VM install with the audio from the test tome cart. The problem still exists in my 4.x install.

Third, I have made a backup sql of the 4.x system and gzip'ed it. it is 44K in size. I would be happy to make it available if Fred or David wants to try and restore it and see if the problem moves with the database.

David, Fred's steps are incomplete to see the problem. I can see the Alab group in the groups dropdown and I can select it. Once selected, I can see the cart in the group. The problem is, I cannot see the Alab group when All groups are selected. Did you try watching the webm video I uploaded?

**Comment by dzkahn** [comment] 2022-10-04 20:32
I am the one that found this problem and asked about it in the facebook Rivendell group.  I can probably give a copy of our database as well. I would have to edit out some passwords and I wouldn't want to post it publicly.  I transferred it from our onair machine that is running 3.5.  The original database might have been created 11 years ago.

**Comment by dklann** [comment] 2022-10-05 03:31
Hey @zotz, I'd be happy to load your database on my system (or yours @dzkahn). @zotz, at that small size you should be able to attach it to an email. Feel free to send it to any of the email addresses you have for me (or see [my github main page](https://github.com/dklann) for a good current address).

**Comment by zotz** [comment] 2022-10-07 18:04
dklann, did you get my email with the attachments yet?

drew

**Comment by dklann** [comment] 2022-10-10 13:15
> dklann, did you get my email with the attachments yet?
> 
> drew

I did get the attachments @zotz, I've been distracted with a family visit. Will load that database today and see how it goes on 4.4.0rc1.

**Comment by dklann** [comment] 2022-10-12 03:00
Still unable to reproduce this issue.

I loaded the database provided by @zotz on my Rivendell 4.0.0rc1 system this evening (OS: Linux Mint 21). I made the following changes from my default installation:
* changed the hostname with `sudo hostnamectl hostname riv4-vb`
* loaded @zotz database with `mysql Rivendell < rdlibissue_40x.sql`(with appropriate credentials)
* ran `sudo rddbmgr --modify` in order for Rivendell services to properly start (database version difference prevented service startup)
* rebooted

After these steps I logged in as Linux user _rd_ and ran both _RDAirplay_ and _RDLibrary_. I could see Cart number 712345 (in Group "_Alab_") in both applications with Group "All" selected in the dropdown (and also with Group "_Alab_" selected in the dropdown).

Please correct me if I did not follow steps as shown in the screen capture or in your list of steps to reproduce.

**Comment by zotz** [comment] 2022-10-13 13:02
If I read you right, I think you are doing what is needed to see the issue but not seeing it.

Would it be asking too much for you to take a screenshot equivalent to the first image in the issue thread? Or even a short video like this one linked to above: 

[rivbug829_01.webm](https://user-images.githubusercontent.com/614926/193412930-bb0554ec-9426-4fa7-96c3-0e110d2db778.webm)

Could it have been solved between b3 and rc0? I will report back when rc0 gets delivered to me via update.

**Comment by ElvishArtisan** [comment] 2022-10-13 14:29
> Could it have been solved between b3 and rc0? I will report back when rc0 gets delivered to me via update.

Absolutely. There have been hundreds of modifications between those two versions. Almost a thousand lines of ```ChangeLog``` entries (figure, around 200 commits).

**Comment by ElvishArtisan** [comment] 2022-10-13 14:33
> I will report back when rc0 gets delivered to me via update.

Should be in the repo now. Just do:
```sudo apt update```
```sudo apt upgrade```

N.B. -- this will upgrade _all_ of the packages on your system!

**Comment by zotz** [comment] 2022-10-14 12:35
@ElvishArtisan

apt commands just gets me to 4.0.0beta3-1 (per synaptic) Problem remains for me at that "level"...
apt list --upgradable shows nothing to upgrade

@dklann Thanks.

**Comment by ElvishArtisan** [comment] 2022-10-14 15:14
Are you on Ubuntu Jammy (22.04)? We quit making packages for Focal (20.04) awhile back.

**Comment by zotz** [comment] 2022-10-15 01:57
@ElvishArtisan 

I was on focal, did an upgrade to jammy added new repos etc. now on rc0 and problem is gone.

Thanks.

Now I have to try and figure out the correct way to get promiscuous jack working smoothly and trouble free and I may just be ready for the future when it arrives.

@dzkahn ... this may help you.

**Comment by ElvishArtisan** [comment] 2022-10-17 13:48
Promiscuous jack should mostly "just work". The biggest stubling block I've run across has been ensuring that your JACK implementation actually supports it. The one packaged with CentOS 7 does not, but the Jammy one works fine. With the advent of Pipewire (see #823) we now have _three_ different implementations of the JACK system, with no method of testing for the support of promiscuous mode other than just trying it. I've yet to do compreshensive testing against all of them.

**Comment by zotz** [comment] 2022-10-17 17:08
[Promiscuous jack should mostly "just work".]

I have seen that statement, I cannot yet get it to just work on boot with how I am used to starting things as a base.

[The biggest stumbling block I've run across has been ensuring that your JACK implementation actually supports it.]

My jack (jammy) does support it. I have user rd and have created another user rd1 who is a member of audio. promiscuous more work between them automatically. The problem is getting rivendell to start and use the same "jack graph"... I can force things by stopping all jack related things and restarting after playing about manually, but I have not yet sorted it all.

If someone has a working example as a base, I would love to learn how things are being done and save myself a bit of time.

**Comment by ElvishArtisan** [comment] 2022-10-21 16:35
Closing this issue as the 'missing carts' problem appears to be sorted. Feel free to open a new one for JACK issues if required.

**Closed by ElvishArtisan** 2022-10-21 16:35 UTC
Labels: question
