### ISSUE TITLE
Cue Card Set To None Causing Crash of RDAirplay

### ISSUE THREAD

**Issue by WMTH** [ElvishArtisan/rivendell#828] opened 2022-09-28 12:32 UTC
In Rivendell 4.0.0beta2int4-092722 build, selecting "none" for Cue Output  Card causes RDAirplay to crash when selecting cart in the Cart Select box.  This issue began today after compiling and installing the code of 9-27-22.  If a Cur Output Card and Port is selected, RDAirplay functions normally.

**Comment by ElvishArtisan** [comment] 2022-09-29 18:00
Confirmed here.

**Comment by ElvishArtisan** [comment] 2022-09-29 18:07
Silly regression caused by the fix for #824. Fixed in af4fec0. Please test!

**Comment by WMTH** [comment] 2022-09-29 20:19
Applied fix, regression cured (functions as intended).

**Comment by ElvishArtisan** [comment] 2022-09-29 20:22
Thanks!

**Closed by ElvishArtisan** 2022-09-29 20:22 UTC
Labels: bug, question
