### ISSUE TITLE
Font issues with fresh install of RD 3.1.0

### ISSUE THREAD

**Issue by McInTEC** [ElvishArtisan/rivendell#505] opened 2019-10-22 21:40 UTC
I installed the new version of Rivendell fresh using the guide http://static.paravelsystems.com/rivendell-install-rd3/rivendell-install-rhel7.html

However the new version is showing the top of the text cut off in the top columns label in Select Cart of RDAirPlay and RDLibrary and the log itself in AirPlay. Would this have anything to do with Fonts or themes of XFCE? I am just using the standard theme that comes installed after running the script.

I would show you a screenshot but GitHub won't let me upload a screenshot at the moment.

**Comment by ElvishArtisan** [comment] 2019-10-23 13:23
Known issue (actually caused by a rebasing of the fonts by RedHat in the 7.7 CentOS update).
Already fixed in 'master', will appear in the next regular release.

**Comment by McInTEC** [comment] 2019-10-23 17:37
Will this be as easy as doing yum -y update?

I did this on our RD2.19.3 and it messed up the text in the player decks.

**Comment by ElvishArtisan** [comment] 2019-10-28 19:50
Fixed in 9709016, 13fe76b, 8be7931, bbdf522, e7812d3, e81256b, 912f54b, b11e07a, d4bfe38, 93e40d4, 2c5c788, c8ed729, 4c41f7f, 8f5dd2a, 84d4696, ecf328e, 6f0fb28, 36b8e00, 640440a, 247a3cd, 8ca15c7 and f18dacf.

These fixes will appear as part of the next regular release of Rivendell [v3.2.0]. You'll need to make the jump from v2.x to v3.x to get this. See:

http://wiki.rivendellaudio.org/index.php/Upgrading_from_v2_to_v3_on_CentOS_7.

**Closed by ElvishArtisan** 2019-10-28 19:50 UTC
