### ISSUE TITLE
RdAirPlay Columns cannot be reordered

### ISSUE THREAD

**Issue by ctecamp** [ElvishArtisan/rivendell#728] opened 2021-09-15 01:42 UTC
The Columns can't be moved as in previous versions.
Ubuntu Studio 20.04

**Comment by ElvishArtisan** [comment] 2021-09-15 15:23
Known problem. That functionality appears to have been removed from the relevant Qt classes in the change from Qt4 to Qt5.

**Comment by ElvishArtisan** [comment] 2021-09-21 17:14
Fixed in d1db7e7. Please test!

**Comment by alexolivan** [comment] 2021-09-22 11:36
Didn't notice about neither the feature nor the regression on it.... However, I have just apt-upgraded and I think it works for me: I can drag columns re-ordering them.

**Closed** 2021-09-22 14:39 UTC
Labels: bug, question
