### ISSUE TITLE
Client-Server Possible Mysql issue

### ISSUE THREAD

**Issue by caryhon139** [ElvishArtisan/rivendell#781] opened 2022-03-01 06:17 UTC
I had to rebuild the beta 3 network after an hdd crash. When I rebuilt everything I couldn't get the client to connect to the database. The issue is in the /etc/msql/mariadb.conf.d/50-server.cnf. The bind address should have been set to 0.0.0.0 but is set to 127.0.0.1 If you don't change it then no clients can connect. I would have thought that if this was a server install then that setting should have been set during the install. I don't see any documentation or hints relating to this item. With the 3.6 install there is a note to change it in the mysql.cnf file which really doesn't exist on the 4.0 beta 3 installation. Maybe this was done on purpose?

**Comment by ElvishArtisan** [comment] 2022-03-01 17:41
Good catch!

The problem is actually a typo in the name of the '/etc/mysql/mariadb.conf.d/90-rivendell.conf' configuration snippet (provided by the Rivendell installer), which contains a statement to override that bind-address value. That snippet ought to be named: '/etc/mysql/mariadb.conf.d/90-rivendell.cnf'.

**Comment by ElvishArtisan** [comment] 2022-03-01 18:31
Fixed in 07bb76c in https://github.com/ElvishArtisan/ubuntu-rivendell-installer.

**Closed by ElvishArtisan** 2022-03-01 18:31 UTC
Labels: bug

**Comment by caryhon139** [comment] 2022-03-01 21:44
I aim to please.

_ Cary _
