### ISSUE TITLE
Scheduler Rules: Log Generation Problem using "Do Not Schedule After"

### ISSUE THREAD

**Issue by McInTEC** [ElvishArtisan/rivendell#388] opened 2019-03-17 19:31 UTC
Hello,

I am having problems when Generating logs. Whenever I specify anything in "Do Not Schedule After", "Or After" in the scheduler rules it does not generate a full hour log. Only 3 Events and then the next hour.
I am wondering what I am doing wrong? If I leave the Schedule After blank it generates a proper log.

Thanks for your help

-Jason

Photo Attached.

![RDProblemGen](https://user-images.githubusercontent.com/48656929/54496783-a1b30080-48c9-11e9-89f1-8b8c7c145d15.PNG)

**Comment by deltecent** [comment] 2019-03-31 17:37
I can confirm that I broke this when moving scheduler codes from ```CART``` to ```CART_SCHED_CODES```. I will submit a PR to fix it.

**Comment by McInTEC** [comment] 2019-03-31 17:40
Thank you. It hasn't worked since I found Rivendell back in November 2018. I tried this on multiple machines using the CentOS install instructions on the wiki.

**Comment by deltecent** [comment] 2019-04-02 02:31
I'm looking at the code and I'm not sure if this ever worked, at least not how I would expect it to work. Since the clock "Scheduler Codes" dialog isn't documented, and neither is code, it is not clear what the intention was.

@McInTEC , would you mind describing what it is you're expecting "Do Not Schedule After" to do?

**Comment by McInTEC** [comment] 2019-04-02 02:51
Well essentially I am playing songs without jingles between all of them and want smooth transitions between songs. Having a fast song go into a soft slow song sounds a bit odd. but if you go from fast to medium temp feeling of a song then you can move from med temp into slower songs, then go back into medium temp songs and then back to fast. But it isn't only that. If I just simply set anything in do not it does not work right. So if I say not to schedule a a 1990s song to play after a 2000s song it does not work. The earlier version of the RRAUbuntu RRAKStudio did not work either.

I simply followed Brett's guide that I found on the Rivdnell Wiki site https://thebrettblog.wordpress.com/2009/12/31/rivendell-how-to-schedule-music/ But the part with schedule after never worked. However, the other day I tried the 3.0RC00 and it seemed to work. However I have not put it into full test. When I made my schedule rules out in 3.0RC00 the log generated. Now, whether or not the Schedule rules work in RC00 it did generate a full log. But I am confused as how it does not work if the schedule rules feature is there and Brett made a post on it with screen shots? 

I also found a few other odd bugs such as the Pie count to Segue not working properly. Sometimes the next event starts when the pie shows 2, 5 and even 10 second count down left. It doesn't do it with every event/song. Just the odd one. Which is very confusing for a DJ because when it shows and you think there is 10 seconds left the next event starts so the DJ has to be ready in-case it glitches and starts at 10.

I am using the install from the Rivendell Wiki using the scripts in the documentation on different types of systems and I still run into these bugs. The segue count down and music scheduling rules to name a few.

**Comment by deltecent** [comment] 2019-04-02 03:02
@McInTEC -- I think I understand what the code is trying to do now. I'm working on a fix. Thank you for the feedback. I'll also work on adding documentation for those settings into the operations guide.

I'm pretty sure all of the settings in the Scheduler Rules dialog don't work on the 3.0RC00 since I broke saving scheduler codes in the stack (wrongly thinking they were no longer needed).

Regarding the pie in ```rdairplay```, would you mind opening another issue for that?

**Comment by McInTEC** [comment] 2019-04-02 03:07
Thank you so much for the reply and looking to fix this. It would be very handy for it to work!

I will open another issue for the pie problem.

Thanks again! 😊

**Comment by McInTEC** [comment] 2019-04-02 03:17
To reply about the best place for the setting. The clock isn't bad, it is what I am used to. The problem with putting the setting in the event is the fact you can only select one group at a time. I have music put in different groups such as "HOT AC" "CHR" "LGBT" and "INDIE" I also have schedule codes for those groups too. a bit redundant I know but I like organization with my station. If the event allowed you to select multiple groups instead of a group called MUSIC it would work.

For example. all the current top 40 songs are in TOP with schedule code T. T also is set for top songs in the INDIE and LGBT category. All the recurrent popular CHR music is in CHR. When a song moves off the charts and the station charts I create, I change the group of that song from TOP to CHR but I keep the T code assigned as in the clock wheel I specifically set it to play a CHR "T". TOP is for top 40 and CHR with schedule code "T" goes to the top 100 list if that makes sense. So the schedule rules work hand in hand when moving songs to different categories as you can set rules to play a max amount of "T" songs in any given category. But, in the event settings you can only select 1 group with 2 "must have codes". (wish more could be selected)

**Comment by deltecent** [comment] 2019-04-03 01:11
This should be fixed in PR #395

**Closed** 2019-05-03 16:52 UTC
Labels: bug
