### ISSUE TITLE
RDLibrary CD Rip issues in v4.0.0rc0 (Ubuntu 22.04.1 LTS Jammy Jellyfish)

### ISSUE THREAD

**Issue by WLGW-Ops** [ElvishArtisan/rivendell#847] opened 2022-11-29 10:37 UTC
Hi Fred/Team,

I encountered the following error messages while attempting to Rip CD audio to RDLibrary:

1.  CD-Text reader process returned an error!
2. "rdlibrary" is not responding

Despite encountered errors, I was able to import audio into RDLibrary. I was able to replicate this >20 times consistently. I'm happy to pass along any logs etc. as relevant.

![Screenshot from 2022-11-28 21-10-50](https://user-images.githubusercontent.com/119166967/204507024-3ac08438-e921-4790-819e-6bf2ba3e41cd.png)
![Screenshot from 2022-11-28 21-11-07](https://user-images.githubusercontent.com/119166967/204507031-d2e06363-cb45-4b7e-b187-f0e342c8da9f.png)

Best Regards,
Brian
WLGW Operations

**Comment by ElvishArtisan** [comment] 2022-12-01 14:16
Unable to reproduce the problem here using current Git snapshot (f0b000b). I did find and fix the 'CD-Text reader process returned an error []' issue a couple weeks ago, although, weirdly, I cannot find a ```ChangeLog``` record mentioning it.

It's unclear to me how the '"rdlibrary" is not responding' message relates to the above. Is this a separate problem?

**Comment by WLGW-Ops** [comment] 2022-12-01 16:47
It could very well be a case where the '"rdlibrary" is not responding' issue is entirely unrelated to the CD-Text reader issue, however they both occurred during the same workflow of ripping a CD in RDLibrary. Here's a timeline of occurrence that may help:

1. Selecting "Rip CD" in RDLibrary is when the CD-Text reader error occurs
2. After the above, the rdlibrary not responding issue occurs during metadata collection from musicbrainz
3. Once metadata is obtained, the rest of the workflow to rip tracks works as expected

I'll test the current snapshot and keep you posted if either issue is recurrent.

**Comment by ElvishArtisan** [comment] 2022-12-01 19:56
Thanks. I'm going to close this for the time being; feel free to reopen if the problem recurs.

**Closed by ElvishArtisan** 2022-12-01 19:56 UTC
Labels: question
