### ISSUE TITLE
Resetting paused content in Sound Panel throws system log event

### ISSUE THREAD

**Issue by WMTH** [ElvishArtisan/rivendell#311] opened 2018-11-17 19:45 UTC
In testing version 3.0.0-a4 it has been found that resetting a paused content button in the sound panel of RDairplay throws the log event shown below.  Resetting the same event while playing does not render an error.  Testing in the same manner in version 2.19.3 does not result in any errors:

Nov 17 13:34:05 audiodesk rdairplay: invalid SQL or failed DB connection[Column 'EVENT_DATETIME' cannot be null QMYSQL: Unable to execute query]: insert into ELR_LINES set SERVICE_NAME="OnAir",LENGTH=48845470,CART_NUMBER=40001,STATION_NAME="audiodesk",EVENT_DATETIME=NULL,EVENT_TYPE=2,EVENT_SOURCE=4,PLAY_SOURCE=4,CUT_NUMBER=1,TITLE="WLS -Traffic Bed",ARTIST="",PUBLISHER="",COMPOSER="",USAGE_CODE=0,ISRC="",START_SOURCE=1,ALBUM="",LABEL="",ISCI="",DESCRIPTION="Cut 001",OUTCUE="",CONDUCTOR="",USER_DEFINED="",SONG_ID="",ONAIR_FLAG="N"

This error can be replicated with any button that has associated content on any page.

**Comment by ElvishArtisan** [comment] 2018-11-20 18:37
Unable to reproduce this here. Have tried with System and User panels, in both rdairplay(1) and rdpanel(1).

Any other details you could give us that might help to track this down?

**Comment by WMTH** [comment] 2018-11-20 20:33
I ran the tests again, this time on a fresh database (not one that was upgraded) with just the default test tone and I can reproduce consistently, both on a house compiled version and the Paravel distribution (version 3-alpha 4).  The test scenario:


1. Configure RDairplay for sound panel button pausing

2. Open a terminal as root and execute: tail -f /var/log/messages

3. Launch RDairplay

4. Start the test tone in either the system or user panel

5. Pause the test tone

6. Reset the paused button (and the error will appear)


7. Start the test tone again in either panel

8. Reset the playing button without pausing (no error thrown)



Error thrown:


Nov 20 14:14:20 audiodesk rdairplay: DB connection re-established
Nov 20 14:14:20 audiodesk rdairplay: invalid SQL or failed DB connection[Column 'EVENT_DATETIME' cannot be null QMYSQL: Unable to execute query]: insert into ELR_LINES set SERVICE_NAME="Production",LENGTH=51260579,CART_NUMBER=999999,STATION_NAME="audiodesk",EVENT_DATETIME=NULL,EVENT_TYPE=2,EVENT_SOURCE=4,PLAY_SOURCE=4,CUT_NUMBER=1,TITLE="Test Tone",ARTIST="Rivendell Radio Automation",PUBLISHER="",COMPOSER="",USAGE_CODE=0,ISRC="",START_SOURCE=1,ALBUM="",LABEL="",ISCI="",DESCRIPTION="1 kHz at Reference Level [-16 dBFS]",OUTCUE="[tone]",CONDUCTOR="",USER_DEFINED="",SONG_ID="",ONAIR_FLAG="N"


Note for this battery of tests little to no custom configuration has been made (default user, service, etc.).  


Both versions are running the current version of CentOS 7.

**Comment by WMTH** [comment] 2018-11-21 12:55
Good Morning,

 

I extended the testing to RDpanel and have found the same behavior when pausing a button and then resetting; again no error when resetting a button that is playing.  Below is the error thrown by resetting a paused button in RDpanel:

 

Nov 21 06:52:28 audiodesk rdpanel: DB connection re-established

Nov 21 06:52:28 audiodesk rdpanel: invalid SQL or failed DB connection[Column 'EVENT_DATETIME' cannot be null QMYSQL: Unable to execute query]: insert into ELR_LINES set SERVICE_NAME="OnAir",LENGTH=24748829,CART_NUMBER=10157,STATION_NAME="audiodesk",EVENT_DATETIME=NULL,EVENT_TYPE=2,EVENT_SOURCE=4,PLAY_SOURCE=4,CUT_NUMBER=1,TITLE="Classical Gas",ARTIST="Mason Williams",PUBLISHER="",COMPOSER="",USAGE_CODE=0,ISRC="",START_SOURCE=1,ALBUM="The Mason Williams Phonograph Record",LABEL="",ISCI="",DESCRIPTION="Cut 001",OUTCUE="",CONDUCTOR="",USER_DEFINED="",SONG_ID="",ONAIR_FLAG="N"

**Comment by ElvishArtisan** [comment] 2019-05-03 16:58
Is this still occurring with v3.0.0rc01?

**Comment by WMTH** [comment] 2019-05-04 12:27
Tested on v3.0.0rc02 under the conditions outlined in the original problem report and there was no occurrence of the referenced issue.

 

Regards,

**Comment by ElvishArtisan** [comment] 2019-05-04 15:59
Thank you for the update!

I am going to close this issue for now, with the understanding that we can revivie it should the problem recur.

**Closed by ElvishArtisan** 2019-05-04 15:59 UTC
Labels: bug, question
