### ISSUE TITLE
Play appearing even though RDAirplay default is Segue

### ISSUE THREAD

**Issue by CWJR** [ElvishArtisan/rivendell#571] opened 2020-04-28 17:16 UTC
Upgrading to 3.3 from 2.10.3.  In 3.3, when a cart is inserted into the Main log by a macro, from any log machine, the inserted cart is set to a Play transition, regardless of the fact RDAirplay is set to Segue as the default through Admin.  This was not the behavior in 2.10.3 or earlier.

Additionally, if a Segue event is copied from any log (including Main) to another location in the Main log, it also then appears as a Play event in the new location, not Segue as the original event (again, RDAirplay set to Segue as the default transition).

Have not checked other combinations, but these 2 procedures are very common in our setup, and it drastically alters the transition timings and sound.

Appears to be a bug, but I am not qualified to make that call.

--Chuck

**Comment by wilson500** [comment] 2020-06-07 09:58
I was about to report the same issue. I see the same.

**Comment by CWJR** [comment] 2020-06-07 15:40
Situation also present in v3.4.

**Comment by rugger** [comment] 2020-06-22 22:29
I am also seeing this issue in 3,4

**Comment by rugger** [comment] 2020-06-22 22:51
Found the answer in #257 
And checked the Operations Guide and found this:
13.8.22. Insert Cart [PX]
Module rdairplay(1)
Mnemonic PX
131Rivendell Macro Langauge
Insert a cart in a log.
PX mach cart [offset] [PLAY|SEGUE|STOP]!
Insert cart cart after the currently playing or next event plus offset (default '0') lines on log machine
mach. The transition may also be optionally specified.

**Comment by CWJR** [comment] 2020-06-23 04:04
Did you test this?  Specifying a SEGUE transition on my 3.4 installation is ignored and it continues to insert the cart as a Play transition regardless.

Additionally, the ROG says "The transition may also *optionally* be specified."  If RDAdmin has the default transition for a log machine set as Segue, how is not specifying an option but yet having it inserted contrary to the default, considered to be acceptable expected behavior?

Also, even in view of the PX options addition, copying Segue events and pasting results in a Play transition, and this appears to be a related problem.

--Chuck

**Comment by wilson500** [comment] 2020-06-23 08:22
You also see the problem if you copy and paste a cart. It will always be pasted with 'Play'. Moving a cart preserves the correct transition.

**Comment by rugger** [comment] 2020-06-23 11:20
I tested:
1) Add a cart with the ADD Button - Adds with SEGUE
2) Use PX 1 CARTNUMBER SEGUE - Adds With SEGUE  (Offset Works also)
3) Move a Cart within RDAIRPLAY - Moves with SEGUE.

Adding the Transition to the PX command solved my issue, but would agree
that the default should be what happens in all cases.

I did not test the copy initially but can confirm that it does copy with a PLAY transition.

John

**Comment by ElvishArtisan** [comment] 2020-06-23 13:58
Confirmed here.

**Comment by ElvishArtisan** [comment] 2020-06-23 14:34
> Use PX 1 CARTNUMBER SEGUE - Adds With SEGUE (Offset Works also)
**ONLY WORKS WHEN YOU ADD THE OFFSET AND SEGUE OPTIONS TOGETHER**

This is the standard way that multiple optional arguments work in RML. Say you have an RML that can take three optional arguments:

```NN <arg0> <arg1> <arg2>!```

In order to specify a non-default value for ```<arg2>```, explicit values for ```<arg0>``` and ```<arg1>``` _must_ be supplied as well. Otherwise, it can be impossible to disambiguate the intended meaning of the arguments.

Thus, the current implementation is in error in an additional way. Invoking it like this:

```PX 999999 SEGUE!```

should **fail** completely, as it is patently syntactically invalid (whereas right now, it inserts the requested cart with an offset of '0' and a PLAY transition).

**Comment by ElvishArtisan** [comment] 2020-06-23 15:04
Fixed in e223de2. Please test!

**Comment by wilson500** [comment] 2020-06-24 10:07
It fixes the PX macro. That tests fine.  No change to the second part if the bug report:

_Additionally, if a Segue event is copied from any log (including Main) to another location in the Main log, it also then appears as a Play event in the new location, not Segue as the original event (again, RDAirplay set to Segue as the default transition)._

Events still copy with 'PLAY'.

Thanks
Ian.

**Comment by wilson500** [comment] 2020-08-19 22:20
Please could we get a fix for the second part of the bug.

_If a Segue event is copied from any log (including Main) to another location in the Main log, it also then appears as a Play event in the new location, not Segue as the original event (again, RDAirplay set to Segue as the default transition).

Events still copy with 'PLAY'_

Thank you.
Ian.

**Comment by ElvishArtisan** [comment] 2020-10-11 16:54
Fixed in ab0a561. Please test!

**Comment by CWJR** [comment] 2020-10-13 21:14
Thanks for this.  I am not tech savy enough to test before an
official release, but maybe Ian can test.  However, he was not copied
on this email.
--Chuck

**Comment by wilson500** [comment] 2020-10-13 22:25
Hi Chuck.

I got the email as well, and yes I can test.
Hopefully this week.

Ian.

**Comment by wilson500** [comment] 2020-10-14 21:24
Tested OK.
All good.

**Closed** 2020-10-15 13:09 UTC
Labels: bug, question
